language: perl

perl:
    - "5.10"

env:
    PATH=~/.rakudobrew/bin:$PATH

install:
    - git clone https://github.com/tadzik/rakudobrew ~/.rakudobrew
    - rakudobrew build moar
    - rakudobrew build-panda
    - panda install URI
    - panda install Pod::To::HTML
    - panda install LWP::Simple
    - panda install Algorithm::Soundex

script:
    - make test
